### ISSUE TITLE
About UX being slightly weird

### ISSUE THREAD

**Issue by Miepee** [randovania/randovania.github.io#45]
"About" implies youll get a description of the project. instead you just get credits instead. Would probably suffice to just rename it credits instead, considering that the home page is our about page basically?

**Comment by duncathan** [comment]
I don't think this is an issue. this is a very very typical pattern for an About page

**Comment by Miepee** [comment]
not to my knowledge

**Comment by duncathan** [comment]
> "About" implies youll get a description of the project

this just isn't really true. it implies you'll get a description of the people behind the project (consider it short for "About Us", which is what the credits page does
