### ISSUE TITLE
make pages for experimental games

### ISSUE THREAD

**Issue by duncathan** [randovania/randovania.github.io#49]
they don't need to be displayed on the games page itself, but it would be nice if you could visit them via URL

**Comment by Miepee** [comment]
for clarification, is this referring to video DB, main site or both?

**Comment by henriquegemignani** [comment]
ideally we'd have a "dev build" version of the website, so we can test how the website is before a release

**Comment by duncathan** [comment]
> for clarification, is this referring to video DB, main site or both?

both
